#!/usr/bin/env python3
import os
from pathlib import Path
import re

dir_root = Path(os.getcwd())
dir_src = dir_root / "src"
dir_nvim = dir_root / "nvim"
dir_runtime = dir_root / "runtime"


def main() -> None:
    delete_files()
    convert_to_c23()


def convert_to_c23():
    set_c_standard()
    convert_NULL()


def set_c_standard():
    def replace_in_file(fn: Path) -> None:
        txt = fn.read_text()
        txt = txt.replace("-std=gnu99", "-std=gnu23").replace("-std=c99", "-std=c23")
        _ = fn.write_text(txt)

    for f in (
        dir_src / "build_lua.zig",
        dir_root / "build.zig",
        dir_src / "nvim" / "CMakeLists.txt",
        dir_root / "test/unit/preprocess.lua",
    ):
        replace_in_file(dir_src / f)


def convert_NULL():
    pt_null = re.compile(r"\bNULL\b")
    for f in dir_src.rglob("*.c"):
        c = f.read_text()
        c = pt_null.sub("nullptr", c)
        _ = f.write_text(c)
        # print(c)
        # for m in pt_null.finditer(c):
        #     print(f.name, m.group(0))


def delete_files_with_no_syntax(subfolder: str) -> None:
    # delete files in subfolder if there is not associated syntax file

    assert (dir_root / "runtime" / subfolder).exists(), (
        f"Directory `{subfolder}` does exist"
    )

    for f in (dir_root / "runtime" / subfolder).rglob("*.vim"):
        fsn = dir_root / "runtime" / "syntax" / f.name
        if fsn.exists():
            continue
        print(fsn)
        f.unlink()


def delete_files() -> None:
    file_list_delete: list[Path] = [
        dir_nvim / "po/af.po",
        dir_nvim / "po/cs.po",
        dir_nvim / "po/fi.po",
        dir_nvim / "po/ja.po",
        dir_nvim / "po/pt_BR.po",
        dir_nvim / "po/ca.po",
        dir_nvim / "po/da.po",
        dir_nvim / "po/ko.UTF-8.po",
        dir_nvim / "po/ru.po",
        dir_nvim / "po/tr.po",
        dir_nvim / "po/fr.po",
        dir_nvim / "po/nb.po",
        dir_nvim / "po/sk.cp1250.po",
        dir_nvim / "po/uk.po",
        dir_nvim / "po/en_GB.po",
        dir_nvim / "po/ga.po",
        dir_nvim / "po/nl.po",
        dir_nvim / "po/sk.po",
        dir_nvim / "po/vi.po",
        dir_nvim / "po/eo.po",
        dir_nvim / "po/it.po",
        dir_nvim / "po/no.po",
        dir_nvim / "po/sr.po",
        dir_nvim / "po/zh_CN.UTF-8.po",
        dir_nvim / "po/cs.cp1250.po",
        dir_nvim / "po/es.po",
        dir_nvim / "po/ja.euc-jp.po",
        dir_nvim / "po/pl.UTF-8.po",
        dir_nvim / "po/sv.po",
        dir_nvim / "po/zh_TW.UTF-8.po",
        dir_root / "runtime/syntax/8th.vim",
        dir_root / "runtime/syntax/a65.vim",
        dir_root / "runtime/syntax/abaqus.vim",
        dir_root / "runtime/syntax/abel.vim",
        dir_root / "runtime/syntax/acedb.vim",
        dir_root / "runtime/syntax/aflex.vim",
        dir_root / "runtime/syntax/ahdl.vim",
        dir_root / "runtime/syntax/aidl.vim",
        dir_root / "runtime/syntax/algol68.vim",
        dir_root / "runtime/syntax/amiga.vim",
        dir_root / "runtime/syntax/aml.vim",
        dir_root / "runtime/syntax/ampl.vim",
        dir_root / "runtime/syntax/art.vim",
        dir_root / "runtime/syntax/asn.vim",
        dir_root / "runtime/syntax/aspperl.vim",
        dir_root / "runtime/syntax/aspvbs.vim",
        dir_root / "runtime/syntax/astro.vim",
        dir_root / "runtime/syntax/asy.vim",
        dir_root / "runtime/syntax/atlas.vim",
        dir_root / "runtime/syntax/autopkgtest.vim",
        dir_root / "runtime/syntax/ave.vim",
        dir_root / "runtime/syntax/avra.vim",
        dir_root / "runtime/syntax/ayacc.vim",
        dir_root / "runtime/syntax/b.vim",
        dir_root / "runtime/syntax/baan.vim",
        dir_root / "runtime/syntax/bc.vim",
        dir_root / "runtime/syntax/bdf.vim",
        dir_root / "runtime/syntax/bsdl.vim",
        dir_root / "runtime/syntax/bst.vim",
        dir_root / "runtime/syntax/cangjie.vim",
        dir_root / "runtime/syntax/cdl.vim",
        dir_root / "runtime/syntax/chill.vim",
        dir_root / "runtime/syntax/cmod.vim",
        dir_root / "runtime/syntax/cmusrc.vim",
        dir_root / "runtime/syntax/coco.vim",
        dir_root / "runtime/syntax/conaryrecipe.vim",
        dir_root / "runtime/syntax/crm.vim",
        dir_root / "runtime/syntax/csdl.vim",
        dir_root / "runtime/syntax/csp.vim",
        dir_root / "runtime/syntax/cupl.vim",
        dir_root / "runtime/syntax/cynlib.vim",
        dir_root / "runtime/syntax/cynpp.vim",
        dir_root / "runtime/syntax/dcd.vim",
        dir_root / "runtime/syntax/dcl.vim",
        dir_root / "runtime/syntax/def.vim",
        dir_root / "runtime/syntax/denyhosts.vim",
        dir_root / "runtime/syntax/desc.vim",
        dir_root / "runtime/syntax/dictconf.vim",
        dir_root / "runtime/syntax/dictdconf.vim",
        dir_root / "runtime/syntax/diva.vim",
        dir_root / "runtime/syntax/dtml.vim",
        dir_root / "runtime/syntax/dylan.vim",
        dir_root / "runtime/syntax/ecd.vim",
        dir_root / "runtime/syntax/edif.vim",
        dir_root / "runtime/syntax/esqlc.vim",
        dir_root / "runtime/syntax/esterel.vim",
        dir_root / "runtime/syntax/euphoria3.vim",
        dir_root / "runtime/syntax/euphoria4.vim",
        dir_root / "runtime/syntax/eviews.vim",
        dir_root / "runtime/syntax/falcon.vim",
        dir_root / "runtime/syntax/fan.vim",
        dir_root / "runtime/syntax/fasm.vim",
        dir_root / "runtime/syntax/fdcc.vim",
        dir_root / "runtime/syntax/fgl.vim",
        dir_root / "runtime/syntax/flexwiki.vim",
        dir_root / "runtime/syntax/focexec.vim",
        dir_root / "runtime/syntax/form.vim",
        dir_root / "runtime/syntax/foxpro.vim",
        dir_root / "runtime/syntax/fpcmake.vim",
        dir_root / "runtime/syntax/framescript.vim",
        dir_root / "runtime/syntax/freebasic.vim",
        dir_root / "runtime/syntax/gdmo.vim",
        dir_root / "runtime/syntax/gel.vim",
        dir_root / "runtime/syntax/gift.vim",
        dir_root / "runtime/syntax/gnash.vim",
        dir_root / "runtime/syntax/gp.vim",
        dir_root / "runtime/syntax/grads.vim",
        dir_root / "runtime/syntax/gretl.vim",
        dir_root / "runtime/syntax/gvpr.vim",
        dir_root / "runtime/syntax/haskell.vim",
        dir_root / "runtime/syntax/hlsplaylist.vim",
        dir_root / "runtime/syntax/hog.vim",
        dir_root / "runtime/syntax/hollywood.vim",
        dir_root / "runtime/syntax/ibasic.vim",
        dir_root / "runtime/syntax/icemenu.vim",
        dir_root / "runtime/syntax/icon.vim",
        dir_root / "runtime/syntax/idl.vim",
        dir_root / "runtime/syntax/idlang.vim",
        dir_root / "runtime/syntax/inform.vim",
        dir_root / "runtime/syntax/initex.vim",
        dir_root / "runtime/syntax/initng.vim",
        dir_root / "runtime/syntax/inittab.vim",
        dir_root / "runtime/syntax/ipfilter.vim",
        dir_root / "runtime/syntax/ishd.vim",
        dir_root / "runtime/syntax/iss.vim",
        dir_root / "runtime/syntax/ist.vim",
        dir_root / "runtime/syntax/j.vim",
        dir_root / "runtime/syntax/jal.vim",
        dir_root / "runtime/syntax/jam.vim",
        dir_root / "runtime/syntax/jargon.vim",
        dir_root / "runtime/syntax/jess.vim",
        dir_root / "runtime/syntax/jgraph.vim",
        dir_root / "runtime/syntax/jjdescription.vim",
        dir_root / "runtime/syntax/jovial.vim",
        dir_root / "runtime/syntax/karel.vim",
        dir_root / "runtime/syntax/kix.vim",
        dir_root / "runtime/syntax/krl.vim",
        dir_root / "runtime/syntax/kscript.vim",
        dir_root / "runtime/syntax/kwt.vim",
        dir_root / "runtime/syntax/lace.vim",
        dir_root / "runtime/syntax/latte.vim",
        dir_root / "runtime/syntax/lc.vim",
        dir_root / "runtime/syntax/lftp.vim",
        dir_root / "runtime/syntax/lifelines.vim",
        dir_root / "runtime/syntax/lilo.vim",
        dir_root / "runtime/syntax/lisp.vim",
        dir_root / "runtime/syntax/lite.vim",
        dir_root / "runtime/syntax/litestep.vim",
        dir_root / "runtime/syntax/lotos.vim",
        dir_root / "runtime/syntax/lout.vim",
        dir_root / "runtime/syntax/lpc.vim",
        dir_root / "runtime/syntax/lprolog.vim",
        dir_root / "runtime/syntax/lscript.vim",
        dir_root / "runtime/syntax/lsl.vim",
        dir_root / "runtime/syntax/lss.vim",
        dir_root / "runtime/syntax/lynx.vim",
        dir_root / "runtime/syntax/lyrics.vim",
        dir_root / "runtime/syntax/m17ndb.vim",
        dir_root / "runtime/syntax/m3build.vim",
        dir_root / "runtime/syntax/m3quake.vim",
        dir_root / "runtime/syntax/maple.vim",
        dir_root / "runtime/syntax/masm.vim",
        dir_root / "runtime/syntax/master.vim",
        dir_root / "runtime/syntax/maxima.vim",
        dir_root / "runtime/syntax/mel.vim",
        dir_root / "runtime/syntax/mf.vim",
        dir_root / "runtime/syntax/mgl.vim",
        dir_root / "runtime/syntax/mgp.vim",
        dir_root / "runtime/syntax/mib.vim",
        dir_root / "runtime/syntax/mix.vim",
        dir_root / "runtime/syntax/mma.vim",
        dir_root / "runtime/syntax/mmix.vim",
        dir_root / "runtime/syntax/modsim3.vim",
        dir_root / "runtime/syntax/monk.vim",
        dir_root / "runtime/syntax/moo.vim",
        dir_root / "runtime/syntax/mp.vim",
        dir_root / "runtime/syntax/mplayerconf.vim",
        dir_root / "runtime/syntax/mrxvtrc.vim",
        dir_root / "runtime/syntax/msidl.vim",
        dir_root / "runtime/syntax/msmessages.vim",
        dir_root / "runtime/syntax/msql.vim",
        dir_root / "runtime/syntax/mss.vim",
        dir_root / "runtime/syntax/mupad.vim",
        dir_root / "runtime/syntax/murphi.vim",
        dir_root / "runtime/syntax/mush.vim",
        dir_root / "runtime/syntax/n1ql.vim",
        dir_root / "runtime/syntax/nastran.vim",
        dir_root / "runtime/syntax/natural.vim",
        dir_root / "runtime/syntax/ncf.vim",
        dir_root / "runtime/syntax/nqc.vim",
        dir_root / "runtime/syntax/nsis.vim",
        dir_root / "runtime/syntax/nu.vim",
        dir_root / "runtime/syntax/obj.vim",
        dir_root / "runtime/syntax/obse.vim",
        dir_root / "runtime/syntax/occam.vim",
        dir_root / "runtime/syntax/omnimark.vim",
        dir_root / "runtime/syntax/ondir.vim",
        dir_root / "runtime/syntax/openroad.vim",
        dir_root / "runtime/syntax/opl.vim",
        dir_root / "runtime/syntax/ora.vim",
        dir_root / "runtime/syntax/papp.vim",
        dir_root / "runtime/syntax/pccts.vim",
        dir_root / "runtime/syntax/pf.vim",
        dir_root / "runtime/syntax/pfmain.vim",
        dir_root / "runtime/syntax/pic.vim",
        dir_root / "runtime/syntax/pike.vim",
        dir_root / "runtime/syntax/pilrc.vim",
        dir_root / "runtime/syntax/pine.vim",
        dir_root / "runtime/syntax/pinfo.vim",
        dir_root / "runtime/syntax/pli.vim",
        dir_root / "runtime/syntax/plm.vim",
        dir_root / "runtime/syntax/plp.vim",
        dir_root / "runtime/syntax/poefilter.vim",
        dir_root / "runtime/syntax/poke.vim",
        dir_root / "runtime/syntax/ppd.vim",
        dir_root / "runtime/syntax/ppwiz.vim",
        dir_root / "runtime/syntax/pq.vim",
        dir_root / "runtime/syntax/prescribe.vim",
        dir_root / "runtime/syntax/privoxy.vim",
        dir_root / "runtime/syntax/procmail.vim",
        dir_root / "runtime/syntax/progress.vim",
        dir_root / "runtime/syntax/promela.vim",
        dir_root / "runtime/syntax/psf.vim",
        dir_root / "runtime/syntax/psl.vim",
        dir_root / "runtime/syntax/ptcap.vim",
        dir_root / "runtime/syntax/ptx.vim",
        dir_root / "runtime/syntax/purifylog.vim",
        dir_root / "runtime/syntax/pymanifest.vim",
        dir_root / "runtime/syntax/pyrex.vim",
        dir_root / "runtime/syntax/python2.vim",
        dir_root / "runtime/syntax/qb64.vim",
        dir_root / "runtime/syntax/quake.vim",
        dir_root / "runtime/syntax/racc.vim",
        dir_root / "runtime/syntax/radiance.vim",
        dir_root / "runtime/syntax/raml.vim",
        dir_root / "runtime/syntax/rapid.vim",
        dir_root / "runtime/syntax/ratpoison.vim",
        dir_root / "runtime/syntax/rcs.vim",
        dir_root / "runtime/syntax/rcslog.vim",
        dir_root / "runtime/syntax/rebol.vim",
        dir_root / "runtime/syntax/redif.vim",
        dir_root / "runtime/syntax/registry.vim",
        dir_root / "runtime/syntax/remind.vim",
        dir_root / "runtime/syntax/reva.vim",
        dir_root / "runtime/syntax/rexx.vim",
        dir_root / "runtime/syntax/rib.vim",
        dir_root / "runtime/syntax/rnc.vim",
        dir_root / "runtime/syntax/rng.vim",
        dir_root / "runtime/syntax/routeros.vim",
        dir_root / "runtime/syntax/rpcgen.vim",
        dir_root / "runtime/syntax/rpl.vim",
        dir_root / "runtime/syntax/rrst.vim",
        dir_root / "runtime/syntax/rtf.vim",
        dir_root / "runtime/syntax/samba.vim",
        dir_root / "runtime/syntax/sas.vim",
        dir_root / "runtime/syntax/sather.vim",
        dir_root / "runtime/syntax/sbt.vim",
        dir_root / "runtime/syntax/scdoc.vim",
        dir_root / "runtime/syntax/scilab.vim",
        dir_root / "runtime/syntax/screen.vim",
        dir_root / "runtime/syntax/sd.vim",
        dir_root / "runtime/syntax/sdc.vim",
        dir_root / "runtime/syntax/sdl.vim",
        dir_root / "runtime/syntax/sendpr.vim",
        dir_root / "runtime/syntax/sensors.vim",
        dir_root / "runtime/syntax/setserial.vim",
        dir_root / "runtime/syntax/sexplib.vim",
        dir_root / "runtime/syntax/sgf.vim",
        dir_root / "runtime/syntax/sgmldecl.vim",
        dir_root / "runtime/syntax/sgmllnx.vim",
        dir_root / "runtime/syntax/sicad.vim",
        dir_root / "runtime/syntax/sieve.vim",
        dir_root / "runtime/syntax/sil.vim",
        dir_root / "runtime/syntax/simula.vim",
        dir_root / "runtime/syntax/sinda.vim",
        dir_root / "runtime/syntax/sindacmp.vim",
        dir_root / "runtime/syntax/sindaout.vim",
        dir_root / "runtime/syntax/sisu.vim",
        dir_root / "runtime/syntax/skhd.vim",
        dir_root / "runtime/syntax/skill.vim",
        dir_root / "runtime/syntax/sl.vim",
        dir_root / "runtime/syntax/slang.vim",
        dir_root / "runtime/syntax/slice.vim",
        dir_root / "runtime/syntax/slpconf.vim",
        dir_root / "runtime/syntax/slpreg.vim",
        dir_root / "runtime/syntax/slpspi.vim",
        dir_root / "runtime/syntax/slrnrc.vim",
        dir_root / "runtime/syntax/slrnsc.vim",
        dir_root / "runtime/syntax/sm.vim",
        dir_root / "runtime/syntax/smcl.vim",
        dir_root / "runtime/syntax/smil.vim",
        dir_root / "runtime/syntax/smith.vim",
        dir_root / "runtime/syntax/snnsnet.vim",
        dir_root / "runtime/syntax/snnspat.vim",
        dir_root / "runtime/syntax/snnsres.vim",
        dir_root / "runtime/syntax/snobol4.vim",
        dir_root / "runtime/syntax/spajson.vim",
        dir_root / "runtime/syntax/spec.vim",
        dir_root / "runtime/syntax/specman.vim",
        dir_root / "runtime/syntax/spice.vim",
        dir_root / "runtime/syntax/splint.vim",
        dir_root / "runtime/syntax/spup.vim",
        dir_root / "runtime/syntax/spyce.vim",
        dir_root / "runtime/syntax/sqlanywhere.vim",
        dir_root / "runtime/syntax/sqlforms.vim",
        dir_root / "runtime/syntax/sqlhana.vim",
        dir_root / "runtime/syntax/sqlinformix.vim",
        dir_root / "runtime/syntax/sqlj.vim",
        dir_root / "runtime/syntax/sqloracle.vim",
        dir_root / "runtime/syntax/sqr.vim",
        dir_root / "runtime/syntax/squid.vim",
        dir_root / "runtime/syntax/squirrel.vim",
        dir_root / "runtime/syntax/srec.vim",
        dir_root / "runtime/syntax/srt.vim",
        dir_root / "runtime/syntax/ssa.vim",
        dir_root / "runtime/syntax/sshallowedsigners.vim",
        dir_root / "runtime/syntax/sshpublickey.vim",
        dir_root / "runtime/syntax/st.vim",
        dir_root / "runtime/syntax/stata.vim",
        dir_root / "runtime/syntax/stp.vim",
        dir_root / "runtime/syntax/strace.vim",
        dir_root / "runtime/syntax/structurizr.vim",
        dir_root / "runtime/syntax/stylus.vim",
        dir_root / "runtime/syntax/swig.vim",
        dir_root / "runtime/syntax/tads.vim",
        dir_root / "runtime/syntax/tags.vim",
        dir_root / "runtime/syntax/tak.vim",
        dir_root / "runtime/syntax/takcmp.vim",
        dir_root / "runtime/syntax/takout.vim",
        dir_root / "runtime/syntax/tap.vim",
        dir_root / "runtime/syntax/tar.vim",
        dir_root / "runtime/syntax/taskdata.vim",
        dir_root / "runtime/syntax/taskedit.vim",
        dir_root / "runtime/syntax/tasm.vim",
        dir_root / "runtime/syntax/template.vim",
        dir_root / "runtime/syntax/teraterm.vim",
        dir_root / "runtime/syntax/texinfo.vim",
        dir_root / "runtime/syntax/texmf.vim",
        dir_root / "runtime/syntax/tf.vim",
        dir_root / "runtime/syntax/thrift.vim",
        dir_root / "runtime/syntax/tiasm.vim",
        dir_root / "runtime/syntax/tidy.vim",
        dir_root / "runtime/syntax/tilde.vim",
        dir_root / "runtime/syntax/tli.vim",
        dir_root / "runtime/syntax/tolk.vim",
        dir_root / "runtime/syntax/tpp.vim",
        dir_root / "runtime/syntax/trasys.vim",
        dir_root / "runtime/syntax/trustees.vim",
        dir_root / "runtime/syntax/tsalt.vim",
        dir_root / "runtime/syntax/tsscl.vim",
        dir_root / "runtime/syntax/tssgm.vim",
        dir_root / "runtime/syntax/tssop.vim",
        dir_root / "runtime/syntax/tt2.vim",
        dir_root / "runtime/syntax/tt2html.vim",
        dir_root / "runtime/syntax/tt2js.vim",
        dir_root / "runtime/syntax/uc.vim",
        dir_root / "runtime/syntax/uci.vim",
        dir_root / "runtime/syntax/udevconf.vim",
        dir_root / "runtime/syntax/udevperm.vim",
        dir_root / "runtime/syntax/uil.vim",
        dir_root / "runtime/syntax/unison.vim",
        dir_root / "runtime/syntax/updatedb.vim",
        dir_root / "runtime/syntax/upstart.vim",
        dir_root / "runtime/syntax/upstreamdat.vim",
        dir_root / "runtime/syntax/upstreaminstalllog.vim",
        dir_root / "runtime/syntax/upstreamlog.vim",
        dir_root / "runtime/syntax/upstreamrpt.vim",
        dir_root / "runtime/syntax/urlshortcut.vim",
        dir_root / "runtime/syntax/usserverlog.vim",
        dir_root / "runtime/syntax/usw2kagtlog.vim",
        dir_root / "runtime/syntax/valgrind.vim",
        dir_root / "runtime/syntax/vdf.vim",
        dir_root / "runtime/syntax/vera.vim",
        dir_root / "runtime/syntax/virata.vim",
        dir_root / "runtime/syntax/vmasm.vim",
        dir_root / "runtime/syntax/voscm.vim",
        dir_root / "runtime/syntax/vrml.vim",
        dir_root / "runtime/syntax/vroom.vim",
        dir_root / "runtime/syntax/vsejcl.vim",
        dir_root / "runtime/syntax/wdiff.vim",
        dir_root / "runtime/syntax/wdl.vim",
        dir_root / "runtime/syntax/web.vim",
        dir_root / "runtime/syntax/webmacro.vim",
        dir_root / "runtime/syntax/whitespace.vim",
        dir_root / "runtime/syntax/winbatch.vim",
        dir_root / "runtime/syntax/wks.vim",
        dir_root / "runtime/syntax/wml.vim",
        dir_root / "runtime/syntax/wsh.vim",
        dir_root / "runtime/syntax/wsml.vim",
        dir_root / "runtime/syntax/wvdial.vim",
        dir_root / "runtime/syntax/xbl.vim",
        dir_root / "runtime/syntax/xcompose.vim",
        dir_root / "runtime/syntax/xdefaults.vim",
        dir_root / "runtime/syntax/xf86conf.vim",
        dir_root / "runtime/syntax/xinetd.vim",
        dir_root / "runtime/syntax/xkb.vim",
        dir_root / "runtime/syntax/xmath.vim",
        dir_root / "runtime/syntax/xmodmap.vim",
        dir_root / "runtime/syntax/xpm.vim",
        dir_root / "runtime/syntax/xpm2.vim",
        dir_root / "runtime/syntax/xs.vim",
        dir_root / "runtime/syntax/xsd.vim",
        dir_root / "runtime/syntax/xxd.vim",
        dir_root / "runtime/syntax/z8a.vim",
        dir_root / "runtime/syntax/zathurarc.vim",
        dir_root / "runtime/syntax/zimbu.vim",
        dir_root / "runtime/syntax/zir.vim",
        dir_root / "runtime/syntax/zserio.vim",
    ]
    keymaps = [
        "hebrew_cp1255.vim",
        "russian-jcukenwin.vim",
        "arabic_buckwalter.vim",
        "hebrew_iso-8859-8.vim",
        "russian-typograph.vim",
        "arabic_utf-8.vim",
        "hebrewp_cp1255.vim",
        "russian-yawerty.vim",
        "arabic.vim",
        "hebrewp_iso-8859-8.vim",
        "serbian_cp1250.vim",
        "armenian-eastern_utf-8.vim",
        "hebrewp_utf-8.vim",
        "serbian_cp1251.vim",
        "armenian-western_utf-8.vim",
        "hebrewp.vim",
        "serbian_iso-8859-2.vim",
        "azerbaijani.vim",
        "hebrew_utf-8.vim",
        "serbian_iso-8859-5.vim",
        "belarusian-jcuken.vim",
        "hebrew.vim",
        "serbian-latin_utf-8.vim",
        "brazilian_portuguese-abnt.vim",
        "kana.vim",
        "serbian-latin.vim",
        "brazilian_portuguese-compact.vim",
        "kazakh-jcuken.vim",
        "serbian_utf-8.vim",
        "bulgarian-bds.vim",
        "korean-dubeolsik_utf-8.vim",
        "serbian.vim",
        "bulgarian-phonetic.vim",
        "korean.vim",
        "sinhala-phonetic_utf-8.vim",
        "canfr-win.vim",
        "lithuanian-baltic.vim",
        "sinhala.vim",
        "croatian_cp1250.vim",
        "magyar_utf-8.vim",
        "slovak_cp1250.vim",
        "croatian_iso-8859-2.vim",
        "mongolian_utf-8.vim",
        "slovak_iso-8859-2.vim",
        "croatian_utf-8.vim",
        "oldturkic-orkhon_utf-8.vim",
        "slovak_utf-8.vim",
        "croatian.vim",
        "oldturkic-yenisei_utf-8.vim",
        "slovak.vim",
        "czech_utf-8.vim",
        "persian-iranian_utf-8.vim",
        "tamil_tscii.vim",
        "czech.vim",
        "persian.vim",
        "thaana-phonetic_utf-8.vim",
        "dvorak.vim",
        "pinyin.vim",
        "thaana.vim",
        "esperanto_utf-8.vim",
        "polish-slash_cp1250.vim",
        "turkish-f.vim",
        "esperanto.vim",
        "polish-slash_cp852.vim",
        "turkish-q.vim",
        "french-azerty.vim",
        "polish-slash_iso-8859-2.vim",
        "ukrainian-dvorak.vim",
        "georgian-qwerty.vim",
        "polish-slash_utf-8.vim",
        "ukrainian-enhanced.vim",
        "polish-slash.vim",
        "ukrainian-jcuken.vim",
        "vietnamese-telex_utf-8.vim",
        "russian-dvorak.vim",
        "vietnamese-viqr_utf-8.vim",
        "russian-jcukenmac.vim",
        "vietnamese-vni_utf-8.vim",
        "russian-jcuken.vim",
        "russian-jcukenwintype.vim",
    ]

    file_list_delete.extend([dir_runtime / "keymap" / fn for fn in keymaps])

    providers = [
        "node.vim",
        "perl.vim",
        "python3.vim",
        "ruby.vim",
        "script_host.rb",
    ]
    file_list_delete.extend(
        [dir_runtime / "autoload/provider" / fn for fn in providers]
    )
    for fn in file_list_delete:
        if not fn.exists():
            continue
        fn.unlink()

    delete_files_with_no_syntax("indent")
    delete_files_with_no_syntax("queries")
    delete_files_with_no_syntax("ftplugin")
    delete_files_with_no_syntax("compiler")


if __name__ == "__main__":
    main()
